import Head from 'next/head'
import Image from 'next/image'

import Container from '@mui/material/Container'
import Typography from '@mui/material/Typography'
import Stack from '@mui/material/Stack'
import Button from '@mui/material/Button'

import Layout from '../components/Layout'

export default function Home() {
  return <Layout>
    <Head>
      <title>Signup</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>


    <SignupForm />

  </Layout>
}


function SignupForm(){
  const onSubmit = event => {
    event.preventDefault()
    debugger
  }
  return <form {...{onSubmit}}>
    <label for="roll">Roll Number</label>
    <input
      type="text"
      id="roll"
      name="roll"
      required
      minlength="10"
      maxlength="20"
    />
    <label for="name">Name:</label>
    <input type="text" id="name" name="name" required />
    <button type="submit">Submit</button>
  </form>
}
