import Head from 'next/head'
import Image from 'next/image'

import Container from '@mui/material/Container'
import Typography from '@mui/material/Typography'
import Stack from '@mui/material/Stack'
import Button from '@mui/material/Button'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container component="main" maxWidth="lg">
        <Typography variant="h3">
          Welcome to {process.env.APP_NAME}
        </Typography>
        <Stack spacing={2} direction="row">
          <Button variant="text">Text</Button>
          <Button variant="contained">Contained</Button>
          <Button variant="outlined">Outlined</Button>
        </Stack>

        <footer>
          <a
            href="https://www.jlinc.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            {`Powered by JLINC Labs`}
          </a>
        </footer>
      </Container>
    </div>
  )
}
